# Generated by Django 4.2.6 on 2023-11-17 10:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('nearest_town', models.CharField(blank=True, max_length=200, null=True)),
                ('current_insurer', models.CharField(blank=True, max_length=125, null=True)),
                ('intermediary_name', models.CharField(blank=True, max_length=200, null=True)),
                ('engagement_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('anticipated_closure_date', models.DateTimeField(default=datetime.datetime(2023, 11, 24, 10, 33, 38, 246502, tzinfo=datetime.timezone.utc))),
                ('business_class', models.CharField(blank=True, choices=[('', 'Select'), ('MOTOR', 'MOTOR PRIVATE'), ('MOTOR', 'MOTOR COMMERCIAL'), ('ENGINEERING', 'ENGINEERING'), ('FIRE', 'FIRE DOMESTIC'), ('FIRE', 'FIRE INDUSTRIAL'), ('LIABILITIES', 'LIABILITIES'), ('MARINE', 'MARINE'), ('PA', 'PERSONAL ACCIDENT'), ('THEFT', 'THEFT'), ('WIBA', "WORKMEN'S COMPENSATION"), ('MISCELLANEOUS', 'MISCELLANEOUS'), ('MEDICAL', 'MEDICAL')], max_length=15, null=True)),
                ('expected_premium', models.IntegerField(default=0)),
                ('chances_of_closure', models.CharField(blank=True, choices=[('', 'Select'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CLOSED', 'CLOSED')], max_length=15, null=True)),
                ('current_stage', models.CharField(blank=True, choices=[('', 'Select'), ('Prospecting', 'Prospecting'), ('Introduction', 'Introduction'), ('Quotation', 'Quotation'), ('Negotiation', 'Negotiation'), ('KYC', 'KYC Collection'), ('Payment', 'Payment'), ('Debiting', 'Debiting'), ('Closed', 'Closed'), ('Lost', 'Lost')], max_length=15, null=True)),
                ('additional_remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
